Cleanroom:
  mqtt_topic: /environment/HumAndTemp001/#
Coldroom:
  co2_sensor_topic: /ble/CO2-1
  mqtt_topic: /coldroom/#
  shellies_air_topic: /shellies/coldroomair/status/switch:0
MARTA:
  mqtt_topic: /MARTA/#
ThermalCamera:
  mqtt_topic: /thermalcamera/#
  stitch_camera: camera0
mqtt:
  broker: 192.168.0.45
  port: 1883
