api_base_url: http://localhost:5000
check_id_command: check_id.sh --module {module_id} --position {position} --fc7 {fiber_endpoint}
dark_test_command: /bin/true
db_endpoint: http://localhost:5000/modules
fiber_endpoint: connect
fiber_method: POST
light_on_command: light_on_test.sh --ring {ring_id} --pos {position} --fiber {fiber}
mqtt_server: test.mosquitto.org
mqtt_topic: /ar/thermal/image
power_endpoint: connect
power_method: POST
